### ISSUE TITLE
hi, would like to consult some doubt, pls read inside

### ISSUE THREAD

**Issue by pmxtek** [yesmore/italk-uniapp#1]
你好 你的demo很棒，但是我有几个问题想问，我只是个萌新= =
1、你的项目使用了express，但是却没有express默认创建的bin\www，而是直接在app.js调用了app.listen，这样实际运行中有什么差别吗？这样用有什么优势？
2、require('./router/index')(app) 这个写法与app.use什么区别吗

**Comment by bai-23** [comment]
1. 如你所见，这个项目并没有使用express脚手架，而是手动创建，与默认创建有所区别，但是这并不影响程序运行，也就是差别不大。
2. `require() `是nodejs的模块加载语法，我认为其作用可以**类似于匿名的自执行函数**：
```js
(function(){
    // 你的代码。
})();
```
3. app.use()里面使用的参数，主要是函数。但这个使用，并不是函数调用，而是使能的意思。当用户在浏览器发出请求的时候，这部分函数才会启用，进行过滤、处理。

> tip：本人对nodejs的理解也不够深入，如果您还有疑问，可以试图在百度或者在nodejs/express官网中找到答案，谢谢。
